### ISSUE TITLE
stream data to stdin of exec

### ISSUE THREAD

**Issue by jmls** [patrick-steele-idem/child-process-promise#14]
when execing and exec ;) is it possible to send data to the stdin of the process you are starting

something more sophisticated than  exec("echo 'foo' | someapp")

I have a json object that I want to stringify and pipe to the stdin of a process

thanks

**Comment by patrick-steele-idem** [comment]
This module is just a small wrapper around the native [child_process](https://nodejs.org/api/child_process.html) module. As such, it just passes along the provided arguments directly to the native `exec`, `execFile` or `spawn` methods. You can use the `progress` event to access the native child process instance and from there you have access to [child.stdin](https://nodejs.org/api/child_process.html#child_process_child_stdin), [child.stdout](https://nodejs.org/api/child_process.html#child_process_child_stdout) and [child.stderr](https://nodejs.org/api/child_process.html#child_process_child_stderr).

Since you have access to the input and output streams of the child process you should be able to do everything that you need. Please take a look at the docs for the [child_process](https://nodejs.org/api/child_process.html) module and let me know if you are still stuck or if you think something can be improved in this module.

**Comment by fasiha** [comment]
Thanks for the pointer Patrick! Please forgive this asinine followup, I'm leaving this here just as a tiny example: I wanted to replicate this node-native functionality:
```js
var spawn = require('child_process').spawn;
var s = "hi there!";
var wc = spawn('wc', []);
wc.stdin.write(new Buffer(s));
wc.stdin.end();
wc.stdout.on('data', function(data) {
  console.log("wc said: " + data);
});
```
With child-process-promise, this is what that looks like:
```js
var spawn = require('child-process-promise').spawn;
var s = "hi there!";
var p = spawn('wc', [], { capture: ["stdout"] })
            .progress(function(childProcess) {
              childProcess.stdin.write(new Buffer(s));
              childProcess.stdin.end();
            })
            .then(function(results) { return results })
            .fail(function(err) { console.error('[spawn] ERROR: ', err); });
// ...
p.then(function(results) { console.log("wc said: " + results.stdout); })
```
where the first chunk of code can be in, say, a module, and the last line in a consumer of that module.

🙇!

**Comment by patrick-steele-idem** [comment]
Hey @jmls and @fasiha. Just throwing this out there, but what if we monkey-patched the returned promise object to include a `childProcess` property as shown below:

```javascript
var spawn = require('child-process-promise').spawn;
var s = "hi there!";
var p = spawn('wc', [], { capture: ["stdout"] })
p.childProcess.stdin.write(new Buffer(s));
p.childProcess.stdin.end();
// ...
p.then(function(results) { console.log("wc said: " + results.stdout); })
```

The `progress` event is not part of the native `Promise` specification (only supported by [Q](https://github.com/kriskowal/q) as far as I know). I think monkey-patching the promise object is the lesser of two evils. Any other ideas to simplify the code a bit?

**Comment by fasiha** [comment]
@patrick-steele-idem that would be much clearer!

(Embarrassed to admit it but I didn't know that `progress` was a Q thing, I just used it blindly. But I had no problem converting the resulting promise to a bluebird promise using [`resolve`](https://github.com/petkaantonov/bluebird/blob/master/API.md#promiseresolvedynamic-value---promise).)
