### ISSUE TITLE
Use native promises

### ISSUE THREAD

**Issue by TheSavior** [patrick-steele-idem/child-process-promise#15]
Q is a large dependency for a package like this to have.

**Comment by patrick-steele-idem** [comment]
At the time it was first created Q was the defacto standard. We could switch to a different promise implementation (including a native Promise implentation). If we wanted to maintain backwards compatibility we would need to monkey patch the promise object to support the `progress()` method (and maybe `done()` and `fail()`). Do you have a suggestion for an alternate Promise implementation?

**Comment by qcom** [comment]
[bluebird](https://github.com/petkaantonov/bluebird) is pretty standard these days. the [bookshelf](http://bookshelfjs.org/) orm for example includes its own copy of bluebird.

**Comment by patrick-steele-idem** [comment]
I would welcome a PR to switched to using native promises. This would require that the user either use a new version of Node.js or they would need to manually install a Promise polyfill. Since it would be a breaking change we would need to increment the major version. Thoughts?

This would be really low on my priorities of things to work on so I would welcome a PR. Thanks in advance!

**Comment by sergioalvz** [comment]
IMO, it would be better to let the user to choose which promise library he/she wants to use. Similar projects like [fs-promise](https://github.com/kevinbeaty/fs-promise) are using [any-promise](https://github.com/kevinbeaty/any-promise) (only 667 bytes) for supporting (almost) any kind of promises at runtime.

I wouldn't mind to create a PR for this if you guys agree.

Cheers!

**Comment by patrick-steele-idem** [comment]
Hey @sergioalvz, sorry for being slow to respond. I think there are two options worth considering:

1. Use `any-promise`
2. Just make native `Promise` a requirement and rely on a polyfill being installed by the user if they are using an older version of Node.js

I'm leaning towards Option 2 since it is usually better to stay closer to a standard. What do you think?

**Comment by epixa** [comment]
Native promises are the way to go.  People can always wrap a native promise in another library's promise implementation if they so desire.

**Comment by TheSavior** [comment]
Switching to native promises would mean that the public api would change, removing `.promise` and `.fail` since those aren't part of the spec. Are you comfortable with that change?

**Comment by patrick-steele-idem** [comment]
Hey folks, I finally gave this package some much-needed love and published a new `2.0.0` version that makes use of native ES2015 promises instead of `q`. Other than requiring Node.js 4.0+, I decided to maintain backwards compatibility with `v1.x` of this library by extending the native `Promise` class:

https://github.com/patrick-steele-idem/child-process-promise/blob/master/lib/ChildProcessPromise.js

I also improved the test suite to make sure everything was working as expected.

Please let me know if you see any issues with the new version. Thanks!

**Comment by TheSavior** [comment]
What in particular requires Node 4? I believe Promises are natively in 0.12 as well.

**Comment by patrick-steele-idem** [comment]
I also decided to use some of the ES2015 syntax which I don't think is available in Node.js 0.12

**Comment by epixa** [comment]
Awesome! Thanks a bunch.
