### ISSUE TITLE
[Enhancement] Consider changing to Bluebird

### ISSUE THREAD

**Issue by IanVS** [patrick-steele-idem/child-process-promise#9]
Just a thought, but would you consider replacing q with bluebird?  I keep hearing that it has an order of magnitude better performance, though I have no empirical proof of this myself.

**Comment by patrick-steele-idem** [comment]
At this point, the only change probably worth considering is switching over to using the native Promise type (or a native Promise polyfill). However, my understanding is that the Promise specification doesn't provide support for "progress" events which introduces backwards compatibility problems unless the returned Promise object is monkey-patched to support a `progress` method or some other more appropriate method (which might be okay).

As for performance, unless you are spawning a lot processes, I don't think the performance of promises is going to matter too much. I think "order of magnitude better performance" is a huge stretch since I doubt we are looking at a 10x difference in performance. If Q was significantly slower in the past, I'm sure  that gap has narrowed.

**Comment by IanVS** [comment]
OK thanks, just thought I'd bring it up.
